
language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - NETWORKX_VERSION=1.9
 - NETWORKX_VERSION=1.8
 - NETWORKX_VERSION=1.7
install:
 - pip install networkx==$NETWORKX_VERSION
 - python setup.py install
script:
 - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python ./networkx_viewer/tests.py
